---
dist: trusty
language: python
python: "2.7.12"

# Don't use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run the playbook and hope for no errors
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo

  # Run the playbook one more time and hope for no changes to make sure its idempotent
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Check for the Nagios process
  - ps -ef | grep nagios | grep conf | grep -v grep

  # Check for the listening HTTP port
  - ss -lnt | grep 80

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
