---
env:
  # Provide a list of OSes we want to use for testing.
  - distro: centos7
  - distro: centos8
  - distro: debian9
  - distro: debian10
  - distro: ubuntu1804
services:
  # Tell Travis to start Docker when it brings up an environment.
  - docker
before_install:
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --debug --registry-mirror=https://mirror.gcr.io"'
  - sudo service docker restart
  - docker system info
script:
  # Run tests.
  - ${PWD}/tests/test.sh
notifications:
  # Notify Ansible Galaxy when a role builds successfully.
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
