---
env:
  # Provide a list of OSes we want to use for testing.
  - distro: debian9
  - distro: ubuntu1404
  - distro: ubuntu1604

services:
  # Tell Travis to start Docker when it brings up an environment.
  - docker

script:
  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  # Notify Ansible Galaxy when a role builds successfully.
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

